//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Test.TestRessources", typeof(TestRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .2.4...8.....8...68....71..2..5...9..95.......4..3.........1..7..28...4.....6.3..  11.9 11.9 09.9   
        ///..3....8..5....2.17...........5.8..6.9.12....8....3....6.9....5..4....7.....1.6.2  11.9 11.9 02.6   
        ///..3..6.8....1..2......7...4..9..8.6..3..4...1.7.2.....3....5.....5...6..98.....5.  11.9 01.2 01.2   
        ///1.......9..67...2..8....4......75.3...5..2....6.3......9....8..6...4...1..25...6.  11.8 11.8 11.6   
        ///1....6.8....7..1........5.6..9.4.....7.2...3.8....76..3....1..5.4.9.......2.7....  11.8 11.8 11.6   
        ///.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ElevensHardestSudoku_Small {
            get {
                return ResourceManager.GetString("ElevensHardestSudoku_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ........8..3...4...9..2..6.....79.......612...6.5.2.7...8...5...1.....2.4.5.....3,HardestSudokusThread-00001;tarx0134,tarek,95532,97174,,,,4674,3311
        ///........2..8.1.9..5....3.4....1.93...6..3..8...37......4......53.1.7.8..2........,HardestSudokusThread-00002;tarx0140,tarek,94302,96595,,,,4465,2487
        ///..2...7...1.....6.5......18....37.......49.....41.23....3.2.9...8.....5.6.......2,HardestSudokusThread-00003;tarx0136,tarek,95490,97086,,,,3671,2550
        ///5.......9.2.1...7...8...3...4.6.........5.......2.7.1...3...8. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HardestDatabase110626 {
            get {
                return ResourceManager.GetString("HardestDatabase110626", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.....8.5.3..........7......2.....6.....8.4......1.......6.3.7.5..2.....1.4......
        ///52...6.........7.13...........4..8..6......5...........418.........3..2...87.....
        ///6.....8.3.4.7.................5.4.7.3..2.....1.6.......2.....5.....8.6......1....
        ///48.3............71.2.......7.5....6....2..8.............1.76...3.....4......5....
        ///....14....3....2...7..........9...3.6.1.............8.2.....1.4....5.6.....7.8...
        ///......52..8.4......3...9...5.1...6..2..7........3.....6...1..........7.4.......3.
        ///6.2.5......... [rest of string was truncated]&quot;;.
        /// </summary>
        public static string top95 {
            get {
                return ResourceManager.GetString("top95", resourceCulture);
            }
        }
    }
}
